export const enum InterestType{
    CONTENT_MEDIA = "CONTENT_MEDIA",
    FINTECH = "FINTECH",
    HEALTHCARE_BIO = "HEALTHCARE_BIO",
    EDUCATION_EDUTECH = "EDUCATION_EDUTECH",
    IT_SOFTWARE = "IT_SOFTWARE",
    ECOMMERCE = "ECOMMERCE",
    ETC ="ETC"
}