import {BMCType} from "../../type/BMC/BMC.type";

export const BMCDummyData: BMCType[] = [
    {
        title: "온라인 교육 플랫폼",
        date: new Date("2025-07-01"),
        thumbnail: require('../../assets/images/bmc-thumbnail-exam.png'),
        keyPartners: "콘텐츠 제작자, 강사, 결제 게이트웨이",
        keyActivities: "강의 업로드, 수강 관리, 마케팅",
        keyResources: "플랫폼, 서버, 강사진",
        valuePropositions: "언제 어디서나 학습 가능",
        customerRelationships: "자동 이메일, 고객센터",
        channels: "웹사이트, 앱, 유튜브 광고",
        customerSegments: "대학생, 직장인, 재직자",
        costStructure: "서버 유지비, 강사 수수료, 마케팅 비용",
        revenueStreams: "수강료, 구독 모델",
    },
    {
        title: "배달 음식 플랫폼",
        date: new Date("2025-07-02"),
        thumbnail: require('../../assets/images/bmc-thumbnail-exam.png'),
        keyPartners: "식당, 라이더, 결제 업체",
        keyActivities: "주문 중개, 배송 관리",
        keyResources: "앱, 물류 시스템",
        valuePropositions: "빠른 배달, 다양한 선택",
        customerRelationships: "리뷰 시스템, 실시간 채팅",
        channels: "모바일 앱, SNS",
        customerSegments: "1인 가구, 직장인, 가정",
        costStructure: "마케팅, 배달비 지원, 개발 인건비",
        revenueStreams: "수수료, 프리미엄 광고",
    },
    {
        title: "프리미엄 헬스케어 앱",
        date: new Date("2025-07-03"),
        thumbnail: require('../../assets/images/bmc-thumbnail-exam.png'),
        keyPartners: "병원, 피트니스 센터, 보험사",
        keyActivities: "건강 데이터 수집, 사용자 분석",
        keyResources: "의료 전문가, 개발팀",
        valuePropositions: "개인 맞춤 건강 관리",
        customerRelationships: "AI 상담, 주간 리포트",
        channels: "앱, 이메일, 블로그",
        customerSegments: "건강 관심 있는 성인, 고령자",
        costStructure: "개발, 콘텐츠 제작, 라이센스 비용",
        revenueStreams: "구독, 기업 파트너십",
    },
    {
        title: "중고 거래 앱",
        date: new Date("2025-07-04"),
        thumbnail: require('../../assets/images/bmc-thumbnail-exam.png'),
        keyPartners: "배송 업체, 인증 서비스",
        keyActivities: "상품 매칭, 채팅 기능 제공",
        keyResources: "사용자 커뮤니티, 서버",
        valuePropositions: "안전하고 빠른 중고 거래",
        customerRelationships: "후기 시스템, 신고 기능",
        channels: "앱, 커뮤니티",
        customerSegments: "개인 사용자, 수집가",
        costStructure: "서버 유지, 고객 지원",
        revenueStreams: "광고, 프리미엄 노출",
    },
    {
        title: "AI 번역 서비스",
        date: new Date("2025-07-05"),
        thumbnail: require('../../assets/images/bmc-thumbnail-exam.png'),
        keyPartners: "언어학자, 기업 고객",
        keyActivities: "번역 엔진 개발, 품질 테스트",
        keyResources: "AI 모델, 클라우드 인프라",
        valuePropositions: "정확하고 빠른 실시간 번역",
        customerRelationships: "자동 추천, FAQ",
        channels: "웹, API",
        customerSegments: "글로벌 기업, 여행객",
        costStructure: "GPU 서버 비용, 데이터 수집",
        revenueStreams: "기업 라이선스, API 과금",
    },
    {
        title: "친환경 포장재 스타트업",
        date: new Date("2025-07-06"),
        thumbnail: require('../../assets/images/bmc-thumbnail-exam.png'),
        keyPartners: "재생 플라스틱 업체, 유통사",
        keyActivities: "포장재 개발, 유통",
        keyResources: "기술 인력, 생산설비",
        valuePropositions: "지속가능한 친환경 포장 솔루션",
        customerRelationships: "1:1 상담, 샘플 제공",
        channels: "B2B 영업, 박람회",
        customerSegments: "소비재 기업, 스타트업",
        costStructure: "재료비, 생산비, 인건비",
        revenueStreams: "B2B 계약, OEM 생산",
    },
    {
        title: "반려동물 용품 구독 서비스",
        date: new Date("2025-07-07"),
        thumbnail: require('../../assets/images/bmc-thumbnail-exam.png'),
        keyPartners: "펫 용품 브랜드, 수의사",
        keyActivities: "상품 큐레이션, 정기 배송",
        keyResources: "상품 창고, 전문가 팀",
        valuePropositions: "반려동물 맞춤 용품 정기 배송",
        customerRelationships: "피드백 수집, 맞춤 제안",
        channels: "웹사이트, SNS",
        customerSegments: "반려동물 보호자",
        costStructure: "배송비, 재고 관리, 마케팅",
        revenueStreams: "구독료",
    },
    {
        title: "VR 여행 체험 서비스",
        date: new Date("2025-07-08"),
        thumbnail: require('../../assets/images/bmc-thumbnail-exam.png'),
        keyPartners: "관광청, 콘텐츠 제작사",
        keyActivities: "VR 콘텐츠 제작, 앱 유지보수",
        keyResources: "VR 전문가, 카메라 장비",
        valuePropositions: "집에서 생생하게 여행 체험",
        customerRelationships: "앱 피드백, 커뮤니티 운영",
        channels: "앱스토어, VR 플랫폼",
        customerSegments: "여행 관심 있는 사용자, 교육 기관",
        costStructure: "촬영 비용, 플랫폼 수수료",
        revenueStreams: "콘텐츠 판매, 라이선스",
    },
    {
        title: "온라인 식물 키우기 플랫폼",
        date: new Date("2025-07-09"),
        thumbnail: require('../../assets/images/bmc-thumbnail-exam.png'),
        keyPartners: "화훼농가, 배달업체",
        keyActivities: "식물 추천, 관리 알림 제공",
        keyResources: "데이터베이스, 앱 개발자",
        valuePropositions: "초보도 쉽게 식물 키우기",
        customerRelationships: "관리 알림, 커뮤니티",
        channels: "앱, 인스타그램",
        customerSegments: "홈가드닝 관심자, 도시 거주자",
        costStructure: "마케팅, 물류비",
        revenueStreams: "식물 판매, 구독형 케어",
    },
    {
        title: "프리랜서 매칭 플랫폼",
        date: new Date("2025-07-10"),
        thumbnail: require('../../assets/images/bmc-thumbnail-exam.png'),
        keyPartners: "기업 클라이언트, 프리랜서",
        keyActivities: "매칭 알고리즘, 계약 지원",
        keyResources: "개발팀, 인사 매니저",
        valuePropositions: "프로젝트에 딱 맞는 인재 연결",
        customerRelationships: "채팅 상담, 포트폴리오 관리",
        channels: "웹사이트, 이메일 뉴스레터",
        customerSegments: "중소기업, 프리랜서",
        costStructure: "플랫폼 운영, 인건비",
        revenueStreams: "매칭 수수료, 프리미엄 이용권",
    },
];
